# Generated by Django 6.0.2 on 2026-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0002_auto_20180517_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='others_workitems_from',
            field=models.ManyToManyField(blank=True, to='runtime.workitem'),
        ),
    ]
