# Generated by Django 6.0.2 on 2026-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_process_versioning_sla_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='condition',
            field=models.CharField(blank=True, help_text='ex: eq:APPROVED | timeout:3d | instance.condition=="OK"', max_length=200, null=True),
        ),
    ]
